language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt --upgrade
  - pip install -r requirements.testing.txt --upgrade
  - pip install -e .
  - ./spampy/dataset_downloader.sh

# command to run tests
script:
  - py.test -s -vv --cov-report xml --cov=spampy tests/
  - codecov
